name: CI Pipeline

on:
  push:
    branches: [ "main", "master", "test" ]
  pull_request:
    branches: [ "main", "master", "test" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: |
          echo "Running unit tests..."
          npm run test --if-present

      - name: Build Docker image
        run: docker build -t express-hello-world:latest .

      - name: Notify on Success
        if: success()
        run: |
          echo "Thành công!"
          echo "### :white_check_mark: Pipeline Succeeded!" >> $GITHUB_STEP_SUMMARY
          curl -H "Content-Type: application/json" -d '{"content": "**Thành công:** CI Pipeline dự án Express đã chạy thành công!"}' ${{ secrets.DISCORD_WEBHOOK }}
          
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Thất bại!"
          echo "### :x: Pipeline Failed!" >> $GITHUB_STEP_SUMMARY
          curl -H "Content-Type: application/json" -d '{"content": "**Thất bại:** CI Pipeline dự án Express đã gặp lỗi rùi!"}' ${{ secrets.DISCORD_WEBHOOK }}
